'use client';

import { OwnerLayout } from '@/components/layout/owner-layout';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { 
  FileText, 
  Download, 
  FileSpreadsheet,
  Printer,
  Mail,
  Calendar,
  Filter
} from 'lucide-react';

const reportTemplates = [
  {
    id: 'RPT-001',
    name: 'Production Summary',
    description: 'Daily production output, efficiency, and machine utilization',
    category: 'Production',
    lastGenerated: '2024-01-15',
    format: ['PDF', 'Excel'],
  },
  {
    id: 'RPT-002',
    name: 'Inventory Status',
    description: 'Current stock levels, reorder points, and supplier analysis',
    category: 'Inventory',
    lastGenerated: '2024-01-14',
    format: ['PDF', 'Excel'],
  },
  {
    id: 'RPT-003',
    name: 'Maintenance Report',
    description: 'Machine health scores, upcoming maintenance, and downtime analysis',
    category: 'Maintenance',
    lastGenerated: '2024-01-15',
    format: ['PDF', 'Excel'],
  },
  {
    id: 'RPT-004',
    name: 'Energy Consumption',
    description: 'Monthly energy usage, cost analysis, and carbon footprint',
    category: 'Energy',
    lastGenerated: '2024-01-10',
    format: ['PDF', 'Excel'],
  },
  {
    id: 'RPT-005',
    name: 'Sales Performance',
    description: 'Revenue, profit margins, top customers, and order analysis',
    category: 'Sales',
    lastGenerated: '2024-01-15',
    format: ['PDF', 'Excel'],
  },
  {
    id: 'RPT-006',
    name: 'Worker Productivity',
    description: 'Attendance, performance metrics, and overtime analysis',
    category: 'HR',
    lastGenerated: '2024-01-14',
    format: ['PDF', 'Excel'],
  },
  {
    id: 'RPT-007',
    name: 'AI Insights Report',
    description: 'AI-generated recommendations, predictions, and risk analysis',
    category: 'AI',
    lastGenerated: '2024-01-15',
    format: ['PDF'],
  },
  {
    id: 'RPT-008',
    name: 'Weekly Executive Summary',
    description: 'Comprehensive overview of all factory operations',
    category: 'Executive',
    lastGenerated: '2024-01-14',
    format: ['PDF'],
  },
];

const recentReports = [
  {
    id: 'RPT-001-2024-01-15',
    name: 'Production Summary',
    generatedBy: 'System',
    generatedAt: '2024-01-15 09:00',
    format: 'PDF',
    size: '2.4 MB',
  },
  {
    id: 'RPT-005-2024-01-15',
    name: 'Sales Performance',
    generatedBy: 'Mr. Kumar',
    generatedAt: '2024-01-15 10:30',
    format: 'Excel',
    size: '1.8 MB',
  },
  {
    id: 'RPT-007-2024-01-15',
    name: 'AI Insights Report',
    generatedBy: 'AI System',
    generatedAt: '2024-01-15 08:00',
    format: 'PDF',
    size: '3.2 MB',
  },
];

export default function ReportsPage() {
  const handleExportCSV = () => {
    const csvContent = "data:text/csv;charset=utf-8," 
      + "Report ID,Name,Generated By,Generated At,Format,Size\n"
      + recentReports.map(r => `${r.id},${r.name},${r.generatedBy},${r.generatedAt},${r.format},${r.size}`).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "recent_reports_export.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <OwnerLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-foreground">Reports</h1>
            <p className="text-muted">Generate and download factory reports</p>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" onClick={handleExportCSV}>
              <Download className="w-4 h-4 mr-2" />
              Export Data to CSV
            </Button>
            <Button className="bg-primary hover:bg-primary/90 text-white">
              <FileText className="w-4 h-4 mr-2" />
              Create Custom Report
            </Button>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card className="p-6 hover:shadow-md transition-shadow cursor-pointer">
            <div className="flex items-center space-x-3">
              <div className="p-3 bg-primary/10 rounded-lg">
                <Download className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="font-medium text-foreground">Download PDF</p>
                <p className="text-sm text-muted">Export as PDF</p>
              </div>
            </div>
          </Card>
          <Card className="p-6 hover:shadow-md transition-shadow cursor-pointer">
            <div className="flex items-center space-x-3">
              <div className="p-3 bg-accent/10 rounded-lg">
                <FileSpreadsheet className="w-5 h-5 text-accent" />
              </div>
              <div>
                <p className="font-medium text-foreground">Download Excel</p>
                <p className="text-sm text-muted">Export as Excel</p>
              </div>
            </div>
          </Card>
          <Card className="p-6 hover:shadow-md transition-shadow cursor-pointer">
            <div className="flex items-center space-x-3">
              <div className="p-3 bg-secondary/10 rounded-lg">
                <Printer className="w-5 h-5 text-secondary" />
              </div>
              <div>
                <p className="font-medium text-foreground">Print Report</p>
                <p className="text-sm text-muted">Print directly</p>
              </div>
            </div>
          </Card>
          <Card className="p-6 hover:shadow-md transition-shadow cursor-pointer">
            <div className="flex items-center space-x-3">
              <div className="p-3 bg-warning/10 rounded-lg">
                <Mail className="w-5 h-5 text-warning" />
              </div>
              <div>
                <p className="font-medium text-foreground">Email Report</p>
                <p className="text-sm text-muted">Send via email</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Report Templates */}
        <Card className="p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-semibold text-foreground">Report Templates</h2>
            <div className="flex space-x-2">
              <Button variant="outline" size="sm">
                <Calendar className="w-4 h-4 mr-2" />
                Date Range
              </Button>
              <Button variant="outline" size="sm">
                <Filter className="w-4 h-4 mr-2" />
                Filter
              </Button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {reportTemplates.map((template) => (
              <Card key={template.id} className="p-4 hover:shadow-md transition-shadow">
                <div className="flex items-start justify-between mb-3">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    <FileText className="w-4 h-4 text-primary" />
                  </div>
                  <span className="text-xs text-muted">{template.category}</span>
                </div>
                <h3 className="font-semibold text-foreground mb-1">{template.name}</h3>
                <p className="text-sm text-muted mb-3 line-clamp-2">{template.description}</p>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted">Last: {template.lastGenerated}</span>
                  <div className="flex space-x-1">
                    {template.format.map((fmt) => (
                      <span key={fmt} className="text-xs px-2 py-1 bg-background rounded text-muted">
                        {fmt}
                      </span>
                    ))}
                  </div>
                </div>
                <Button variant="outline" className="w-full mt-3" size="sm">
                  Generate
                </Button>
              </Card>
            ))}
          </div>
        </Card>

        {/* Recent Reports */}
        <Card className="p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-semibold text-foreground">Recent Reports</h2>
            <Button variant="outline" size="sm">
              View All
            </Button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Report ID</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Name</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Generated By</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Generated At</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Format</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Size</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted">Actions</th>
                </tr>
              </thead>
              <tbody>
                {recentReports.map((report) => (
                  <tr key={report.id} className="border-b border-border hover:bg-background">
                    <td className="py-4 px-4 text-sm font-medium text-foreground">{report.id}</td>
                    <td className="py-4 px-4 text-sm text-foreground">{report.name}</td>
                    <td className="py-4 px-4 text-sm text-foreground">{report.generatedBy}</td>
                    <td className="py-4 px-4 text-sm text-muted">{report.generatedAt}</td>
                    <td className="py-4 px-4">
                      <span className="text-xs px-2 py-1 bg-background rounded text-muted">
                        {report.format}
                      </span>
                    </td>
                    <td className="py-4 px-4 text-sm text-muted">{report.size}</td>
                    <td className="py-4 px-4">
                      <div className="flex space-x-2">
                        <Button variant="ghost" size="sm">
                          <Download className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="sm">
                          <Mail className="w-4 h-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Schedule Report */}
        <Card className="p-6 bg-linear-to-r from-primary/5 to-secondary/5 border-l-4 border-l-primary">
          <div className="flex items-start space-x-4">
            <div className="p-3 bg-primary/10 rounded-lg">
              <Calendar className="w-6 h-6 text-primary" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold text-foreground mb-1">Schedule Automated Reports</h3>
              <p className="text-sm text-muted mb-3">
                Set up automatic report generation and delivery to your inbox daily, weekly, or monthly.
              </p>
              <Button variant="outline" size="sm">
                Configure Schedule
              </Button>
            </div>
          </div>
        </Card>
      </div>
    </OwnerLayout>
  );
}
